#!/usr/bin/env ruby

full_report_filename, metrics_filename = ARGV
unless full_report_filename && metrics_filename
  puts 'usage: memory-static <full_report_file> <metrics_filename>'
  exit 1
end

# test
puts full_report_filename
puts metrics_filename
