#!/usr/bin/env ruby

require_relative '../lib/gitlab/popen'

full_report_filename, metrics_filename = ARGV
unless full_report_filename && metrics_filename
  puts 'usage: memory-static-objects <full_report_file> <metrics_filename>'
  exit 1
end

full_report, status = Gitlab::Popen.popen(%w(bundle exec derailed bundle:objects))

unless status.zero?
  puts 'failed to execute the benchmark'
  exit 1
end

File.open(full_report_filename, 'w') do |f|
  f.write(full_report)
end

allocated_str = full_report.lines[1]
retained_str = full_report.lines[2]
allocated_stats = /Total allocated: (?<bytes>.*) bytes \((?<objects>.*) objects\)/.match(allocated_str)
retained_stats = /Total retained: (?<bytes>.*) bytes \((?<objects>.*) objects\)/.match(retained_str)

unless allocated_stats && retained_stats
  puts 'failed to process benchmark output'
  exit 0
end

File.open(metrics_filename, 'w') do |f|
  f.puts "memory_static_objects_bytes_allocated #{allocated_stats[:bytes]}"
  f.puts "memory_static_objects_bytes_retained #{retained_stats[:bytes]}"
  f.puts "memory_static_objects_items_allocated #{allocated_stats[:objects]}"
  f.puts "memory_static_objects_items_retained #{retained_stats[:objects]}"
end

exit 0
