#!/usr/bin/env ruby

require_relative '../lib/gitlab/popen'

full_report_filename, metrics_filename = ARGV
unless full_report_filename && metrics_filename
  puts 'usage: memory-static <full_report_file> <metrics_filename>'
  exit 1
end

full_report, status = Gitlab::Popen.popen(%w(bundle exec derailed bundle:mem))

unless status.zero?
  puts 'failed to execute the benchmark'
  exit 1
end

File.open(full_report_filename, 'w') do |f|
  f.write(full_report)
end

total_mibs_str = /TOP: (.*) MiB/.match(full_report.lines.first)[1]

unless total_mibs_str
  puts 'failed to process the benchmark output'
  exit 1
end

File.open(metrics_filename, 'w') do |f|
  f.puts "memory_static_total_mibs #{total_mibs_str.to_f.round}"
end

exit 0
