.ee-specific-check:
  extends:
    - .default-tags
  dependencies: []
  only:
    - merge_requests@gitlab-org/gitlab-ee

ee-files-location-check:
  extends: .ee-specific-check
  script:
    - scripts/ee-files-location-check

ee-specific-lines-check:
  extends: .ee-specific-check
  script:
    - scripts/ee-specific-lines-check
