.default-tags:
  tags:
    - gitlab-org

.default-retry:
  retry:
    max: 2  # This is confusing but this means "3 runs at max".
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure

.default-before_script:
  before_script:
    - date
    - source scripts/utils.sh
    - source scripts/prepare_build.sh
    - date

# Jobs that only need to pull cache
.default-cache:
  cache:
    key: "debian-stretch-ruby-2.6.3-node-12.x"
    paths:
      - vendor/ruby
      - .yarn-cache/
      - vendor/gitaly-ruby
    policy: pull


.default-only:
  only:
    refs:
      - master
      - /-stable/
      - /^\d+-\d+-auto-deploy-\d+$/
      - merge_requests
      - tags@gitlab-org/gitlab-ce
      - tags@gitlab-org/gitlab-ee
      - tags@gitlab/gitlabhq
      - tags@gitlab/gitlab-ee

.only-code-changes:
  only:
    changes:
      - app/*
      - bin/*
      - config/*
      - db/*
      - ee/*
      - fixtures/*
      - lib/*
      - public/*
      - rubocop/*
      - spec/*
      - symbol/*
      - vendor/*
      - "*.{erb,haml,lock,js,json,rake,ru,png,rb,scss,svg,vue,yml}"
      - "**/*.{erb,haml,lock,js,json,rake,ru,png,rb,scss,svg,vue,yml}"
      - .gitlab/ci/*
      - .gitlab-ci.yml
      - "*_VERSION"
      - Gemfile
      - Rakefile

.only-qa-changes:
  only:
    changes:
      - app/*
      - bin/*
      - config/*
      - db/*
      - ee/*
      - fixtures/*
      - lib/*
      - public/*
      - rubocop/*
      - spec/*
      - symbol/*
      - vendor/*
      - "*.{erb,haml,lock,js,json,rake,ru,png,rb,scss,svg,vue,yml}"
      - "**/*.{erb,haml,lock,js,json,rake,ru,png,rb,scss,svg,vue,yml}"
      - .gitlab/ci/*
      - .gitlab-ci.yml
      - "*_VERSION"
      - Gemfile
      - Rakefile
      - qa/*

.only-docs-changes:
  only:
    changes:
      - doc/*
      - "*.{png,jpg,md}"
      - "**/*.{png,jpg,md}"

.review-only-except:
  only:
    variables:
      - $CI_PROJECT_PATH == "gitlab-org/gitlab-ce"
      - $CI_PROJECT_PATH == "gitlab-org/gitlab-ee"
    kubernetes: active
  except:
    refs:
      - master
      - /^\d+-\d+-auto-deploy-\d+$/

.use-pg:
  services:
    - name: postgres:9.6.14
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:alpine

.use-pg-10:
  image: "dev.gitlab.org:5005/gitlab/gitlab-build-images:ruby-2.6.3-golang-1.11-git-2.22-chrome-73.0-node-12.x-yarn-1.16-postgresql-10-graphicsmagick-1.3.33"
  services:
    - name: postgres:10.9
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:alpine
