# Jobs that only need to pull cache
.dedicated-pull-cache-job:
  extends: .default-config
  cache:
    key: "debian-stretch-ruby-2.6.3-node-12.x"
    paths:
      - vendor/ruby
      - .yarn-cache/
      - vendor/gitaly-ruby
    policy: pull
  stage: test

.no-docs:
  except:
    refs:
      - /(^docs[\/-].+|.+-docs$)/

.no-qa:
  except:
    refs:
      - /(^qa[\/-].*|.*-qa$)/

.only-canonical-master:
  only:
    refs:
      - master@gitlab-org/gitlab-ce
      - master@gitlab-org/gitlab-ee

.no-canonical-master:
  except:
    refs:
      - master@gitlab-org/gitlab-ce
      - master@gitlab-org/gitlab-ee

.single-script-job:
  image: ruby:2.6-alpine
  stage: test
  dependencies: []
  variables:
    GIT_STRATEGY: none
  before_script:
    # We don't clone the repo by using GIT_STRATEGY: none and only download the
    # single script we need here so it's much faster than cloning.
    - export SCRIPT_NAME="${SCRIPT_NAME:-$CI_JOB_NAME}"
    - apk add --update openssl
    - wget $CI_PROJECT_URL/raw/$CI_COMMIT_SHA/scripts/$SCRIPT_NAME
    - chmod 755 $(basename $SCRIPT_NAME)

.use-pg:
  services:
    - name: postgres:9.6.14
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:alpine

.use-pg-10:
  services:
    - name: postgres:10.9
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:alpine
