memory-static:
  extends: .dedicated-no-docs-no-db-pull-cache-job
  script:
    # Uses two different reports from the 'derailed_benchmars' gem.

    # Loads each of gems in the Gemfile and checks how much memory they consume when they are required.
    # 'derailed_benchmarks' internally uses 'get_process_mem'
    - bundle exec derailed bundle:mem > tmp/memory_bundle_mem.txt
    - scripts/generate-gems-size-metrics-static tmp/memory_bundle_mem.txt >> 'tmp/memory_metrics.txt'

    # Outputs detailed information about objects created while gems are loaded.
    # 'derailed_benchmarks' internally uses 'memory_profiler'
    - bundle exec derailed bundle:objects > tmp/memory_bundle_objects.txt
    - scripts/generate-gems-memory-metrics-static tmp/memory_bundle_objects.txt >> 'tmp/memory_metrics.txt'
  artifacts:
    paths:
      - tmp/memory_*.txt
    reports:
      metrics: tmp/memory_metrics.txt

.use-pg-10: &use-pg-10
  services:
    - name: postgres:10.7
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:alpine

memory-on-boot:
  extends: .dedicated-runner
  <<: *use-pg-10
  image: "dev.gitlab.org:5005/gitlab/gitlab-build-images:ruby-2.6.3-golang-1.11-git-2.21-chrome-73.0-node-12.x-yarn-1.16-postgresql-10-graphicsmagick-1.3.29"
  variables:
    NODE_ENV: "production"
    RAILS_ENV: "production"
    SETUP_DB: "true"
    SKIP_STORAGE_VALIDATION: "true"
    WEBPACK_REPORT: "true"
    # we override the max_old_space_size to prevent OOM errors
    NODE_OPTIONS: --max_old_space_size=3584
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  script:
    - yarn install
    - RAILS_ENV=production bundle exec rake webpack:compile
    - RAILS_ENV=production PATH_TO_HIT="/users/sign_in" CUT_OFF=0 bundle exec derailed exec perf:mem >> 'tmp/memory_on_boot_metrics.txt'
  artifacts:
    paths:
      - log/production.log # TODO: remove
      - tmp/memory_on_boot_metrics.txt
