# Insurance in case a gem needed by one of our releases gets yanked from
# rubygems.org in the future.
cache gems:
  extends:
    - .dedicated-pull-cache-job
    - .only-canonical-master
    - .no-docs
  variables:
    SETUP_DB: "false"
  script:
    - bundle package --all --all-platforms
  artifacts:
    paths:
      - vendor/cache
  only:
    refs:
      - tags
  dependencies:
    - setup-test-env

gitlab_git_test:
  extends:
    - .no-docs
    - .no-qa
  variables:
    SETUP_DB: "false"
  before_script: []
  dependencies: []
  script:
    - spec/support/prepare-gitlab-git-test-for-commit --check-for-changes

no_ee_check:
  extends:
    - .no-docs
    - .no-qa
  variables:
    SETUP_DB: "false"
  before_script: []
  dependencies: []
  script:
    - scripts/no-ee-check
  only:
    refs:
      - /.+/@gitlab-org/gitlab-ce
