# Yamllint of *.yml for .gitlab-ci.yml.
# This uses rules from project root `.yamllint`.
lint-ci-gitlab:
  extends:
    - .default-tags
    - .default-retry
    - .default-only
  only:
    changes:
      - .gitlab/ci/*
      - .gitlab-ci.yml
      - "*.yml"
      - "**/*.yml"
  image: sdesbure/yamllint:latest
  dependencies: []
  script:
    - yamllint .gitlab-ci.yml .gitlab/ci lib/gitlab/ci/templates changelogs
