# Yamllint of *.yml for .gitlab-ci.yml.
# This uses rules from project root `.yamllint`.
lint-ci-gitlab:
  image: sdesbure/yamllint:latest
  before_script: []
  dependencies: []
  script:
    - yamllint .gitlab-ci.yml .gitlab/ci lib/gitlab/ci/templates changelogs
